docs_dir: study

site_name: {{ cookiecutter.project_name }}
site_author: {{ cookiecutter.organization }}

repo_name: {{ cookiecutter.organization }}/{{ cookiecutter.project_name }}
repo_url: https://{{ cookiecutter.git_host }}.com/{{ cookiecutter.organization }}/{{ cookiecutter.project_name }}
copyright: <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a> by OASCI

# https://squidfunk.github.io/mkdocs-material/
theme:
  name: material
  custom_dir: study/.overrides
  language: en
  logo: img/harbor-logo-square-white.svg
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: dark
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    annotation: material/star-four-points-circle
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tooltips
    - content.tabs.link
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - navigation.indexes
    - navigation.path
    - navigation.prune
    - toc.follow
    - search.suggest

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

# Options need to be indented twice for some reason?
plugins:
  - search
  - material-plausible
  - mkdocs-jupyter:
        no_input: False
        include_requirejs: true
        include_source: True
        ignore: ["*.py"]
        remove_tag_config:
            remove_input_tags:
                - hide_code
  - awesome-pages:
        collapse_single_pages: true
        strict: false
        order: asc
        sort_type: natural
        order_by: title
  - glightbox
  - macros
  - print-site
  - git-revision-date-localized:
      type: iso_datetime
      timezone: America/Detroit
      fallback_to_build_date: true

hooks:
  - hooks/launchy.py
colab_base_url: https://colab.research.google.com/github/{{cookiecutter.organization}}/{{ cookiecutter.project_name }}/blob/main/study


extra:
  generator: false

extra_css:
  - css/base.css
  - css/colors.css
  - css/mol.css
  - css/mkdocstrings.css
  - https://cdn.jsdelivr.net/npm/molstar@latest/build/viewer/molstar.css

extra_javascript:
  - js/mathjax-config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - abbr
  - toc:
      permalink: true
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
