# https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml
MD013: false
MD022: false
MD024: false
MD026: false
MD028: false
MD031: false
MD032: false
MD033: false
MD036: false
MD038: false
MD041: false
MD046: false
