{% raw %}
name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["{% endraw %}{{ cookiecutter.minimal_python_version }}"{%- if cookiecutter.minimal_python_version != '3.9' -%}, "3.9"{% endif %}]{% raw %}

      steps:
        - name: Checkout repo
          uses: actions/checkout@v4
  
        - name: Install miniconda
          uses: conda-incubator/setup-miniconda@v2
          with:
            miniconda-version: "latest"
            auto-update-conda: true
            python-version: ${{ matrix.python-version }}
  
        - name: Initialize conda environment
          run: make conda-setup
  
        - name: Install conda packages
          run: make from-conda-lock
  
        - name: Poetry install
          run: make install
  
        - name: Run tests
          run: make test

{% endraw %}
