nav:
  - index.md
  - Getting started:
    - get-started/index.md
    - Creating your project: get-started/creating/index.md
    - Project anatomy:
      - get-started/anatomy/index.md
      - Root configuration: get-started/anatomy/root/index.md
      - Source directory: get-started/anatomy/source/index.md
      - Tests directory: get-started/anatomy/tests/index.md
      - Documentation directory: get-started/anatomy/docs/index.md
      - Auxiliary files: get-started/anatomy/aux/index.md
    - Environment: get-started/env/index.md
  - Developer workflow:
    - Developer workflow: workflow/index.md
    - Version control: workflow/version/index.md
    - Coding standards: workflow/standards/index.md
    - Testing: workflow/testing/index.md
    - Debugging: workflow/debug/index.md
  - Usability:
    - usability/index.md
    - Documentation: usability/docs/index.md
    - Packaging:
      - usability/package/index.md
      - Metadata: usability/package/metadata/index.md
      - Build: usability/package/build/index.md
      - Publishing: usability/package/pub/index.md
      - Dependencies: usability/package/deps/index.md
  - Management:
    - manage/index.md
    - CI/CD: manage/cicd/index.md
    - Versioning: manage/versioning/index.md
    - Collaboration: manage/collab/index.md
  - Best practices:
    - bp/index.md
    - Project structure:
      - bp/structure/index.md
      - Hierarchy: bp/structure/hierarchy/index.md
      - Organization: bp/structure/organization/index.md
    - Coding principles:
      - bp/principles/index.md
      - Don't repeat yourself: bp/principles/dry/index.md
      - Keep It Simple, Stupid: bp/principles/kiss/index.md
      - You Aren't Gonna Need It: bp/principles/yagni/index.md
      - Separation of Concerns: bp/principles/soc/index.md
      - SOLID: bp/principles/solid/index.md
      - Avoid premature optimization: bp/principles/opt/index.md
    - Design patterns:
      - bp/patterns/index.md
      - Factory: bp/patterns/factory/index.md
      - Strategy: bp/patterns/strategy/index.md
      - Adapter: bp/patterns/adapter/index.md
      - Observer: bp/patterns/observer/index.md
      - Singleton: bp/patterns/singleton/index.md
      - Command: bp/patterns/command/index.md
      - Decorator: bp/patterns/decorator/index.md
      - Pipeline: bp/patterns/pipeline/index.md
    - Configuration:
      - bp/config/index.md
    - Dependency management: bp/deps/index.md
    - Application programming interface: bp/api/index.md
    - Error handling: bp/errors/index.md
    - Performance and profiling: bp/perf/index.md
    - Security: bp/security/index.md

sort:
  type: natural
  ignore_case: true
  by: title
  direction: asc
flatten_single_child_sections: true
